apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: diskover-web
    context: .
    docker:
      network: host
      dockerfile: Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/diskover-web:{{.VERSION}}'
